import React, {useState,useRef,useEffect,useLayoutEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,useReducedMotion,useMotionValue,useSpring} from 'motion/react';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowUpRight,ArrowRight,ArrowLeft,ArrowDown,GlobeHemisphereWest,Play,Pause,SpeakerSlash,SpeakerHigh,List,X,Copy,Check} from '@phosphor-icons/react';
import '@fontsource-variable/manrope';
import {profile,experience,categories,brands,features,products,campaigns,allProjects,art,imageSizes,closingImage} from './data';
import './style.css';
import BannerShowcase from './components/banner-showcase';
import HeroRipple from './components/hero-ripple';
import IntroSequence from './components/intro-sequence';
gsap.registerPlugin(ScrollTrigger);
const A=import.meta.env.BASE_URL+'assets/';
const toSection=id=>`#/portfolio/${id}`;
const toProject=id=>`#/project/${id}`;
let portfolioReturn=null;
let restorePortfolio=false;

function Reveal({children,className=''}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.7,ease:[.16,1,.3,1]}}>{children}</motion.div>}
function Picture({src,alt,className='',eager=false}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);const dimensions=imageSizes[src]||{};return failed?<div className={`image-error ${className}`} role="img" aria-label={alt}>图片暂时无法载入</div>:<img className={className} src={A+src} alt={alt} width={dimensions.width} height={dimensions.height} loading={eager?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>}
function CopyButton({value,label}){const [state,setState]=useState('idle');const timer=useRef();useEffect(()=>()=>clearTimeout(timer.current),[]);async function copy(){try{await navigator.clipboard.writeText(value);setState('done')}catch{setState('error')}clearTimeout(timer.current);timer.current=setTimeout(()=>setState('idle'),3000)}return <button className="copy-button" onClick={copy} aria-label={`复制${label}`}><span>{value}</span>{state==='done'?<Check/>:<Copy/>}<span className="sr-only" role="status">{state==='done'?`${label}已复制`:state==='error'?`复制失败，请手动复制 ${value}`:''}</span>{state==='done'&&<small>已复制</small>}{state==='error'&&<small>请长按文字手动复制</small>}</button>}
function Nav(){const [open,setOpen]=useState(false);return <header className="site-nav"><a className="wordmark" href={toSection('home')} aria-label="Bess Zhang 首页">BESS<span>®</span></a><nav className={open?'nav-links open':'nav-links'} aria-label="主导航">{[['home','home'],['about','about me'],['work','work'],['contact','contact me']].map(([id,label])=><a key={id} href={toSection(id)} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="nav-contact" href={toSection('contact')}>Let's talk <ArrowUpRight weight="bold"/></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'关闭菜单':'打开菜单'}>{open?<X/>:<List/>}</button></header>}
function Video({intro=false,onEnded}){const ref=useRef();const reduce=useReducedMotion();const [paused,setPaused]=useState(!!reduce);const [muted,setMuted]=useState(true);const [status,setStatus]=useState('loading');useEffect(()=>{const v=ref.current;if(!v)return;if(reduce){v.pause();setPaused(true)}else{v.play().then(()=>setPaused(false)).catch(()=>{setPaused(true);setStatus('ready')})}return()=>v.pause()},[reduce]);return <><video ref={ref} className="ambient-video" src={A+(intro?'intro.mp4':'hero.mp4')} muted={muted} playsInline autoPlay={!reduce} loop={!intro} preload={intro?'auto':'metadata'} onPlaying={()=>{setStatus('ready');setPaused(false)}} onLoadedData={()=>setStatus('ready')} onError={()=>setStatus('error')} onEnded={()=>{setPaused(true);onEnded?.()}} aria-label={intro?'作品集开场影片':'抽象动态背景'}/>{status==='loading'&&<span className="video-state" role="status">Loading film...</span>}{status==='error'&&<span className="video-state" role="status">影片暂时无法播放，可以继续浏览作品。</span>}<div className="video-controls"><button aria-label={paused?'播放视频':'暂停视频'} onClick={()=>{if(paused)ref.current.play().catch(()=>setStatus('error'));else ref.current.pause();setPaused(!paused)}}>{paused?<Play/>:<Pause/>}</button><button aria-label={muted?'开启声音':'静音'} onClick={()=>setMuted(!muted)}>{muted?<SpeakerSlash/>:<SpeakerHigh/>}</button></div></>}
function Entrance(){const [ended,setEnded]=useState(false);const touch=useRef(0);const enter=()=>location.hash='/portfolio/home';return <main className="entrance" onWheel={e=>{if(ended&&e.deltaY>20)enter()}} onTouchStart={e=>touch.current=e.touches[0].clientY} onTouchEnd={e=>{if(ended&&touch.current-e.changedTouches[0].clientY>40)enter()}}><Video intro onEnded={()=>setEnded(true)}/><div className="entrance-top"><span className="wordmark">BESS<span>®</span></span><span>VISUAL DESIGN PORTFOLIO</span></div><div className="entrance-bottom"><div><p>张壁珊 / Bess Zhang</p><span>跨境电商视觉设计师</span></div><a className="entry-link" href={toSection('home')}>{ended?'进入作品集':'Enter portfolio'} <ArrowUpRight/></a></div></main>}
function Hero(){return <section id="home" className="hero"><div className="hero-visual"><Video/><HeroRipple/></div><div className="hero-copy"><p>Design that builds meaningful bonds between brands, products and people.</p><a href={toSection('work')} className="underlink">Explore my work <ArrowUpRight/></a></div><h1 className="hero-type">PORTFOLIO</h1></section>}
function About(){return <section id="about" className="about light-section"><div className="about-main"><div><h2>I build identities<br/>with clarity, purpose,<br/>and a human touch.</h2></div><div className="about-bio"><div><Picture src="portrait.webp" alt="张壁珊个人头像" className="portrait"/><div className="portrait-contact"><strong>contact</strong><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={A+"bess-resume.pdf"} target="_blank" rel="noreferrer">查看完整简历 <ArrowUpRight/></a></div></div><div className="bio-copy"><p>我是 <strong>张壁珊 / Bess Zhang</strong>，<br/>{profile.role}。</p><p>{profile.intro}</p><p>{profile.capability}</p></div></div><div className="about-statement"><h3>Clear thinking.<br/>Distinct visuals.<br/>Consistent experiences.</h3><p>{profile.approach}</p></div></div><aside className="about-aside"><div><h3>education</h3><div className="experience-item"><time>2015.09<br/>2019.06</time><div><strong>肇庆学院</strong><p>园林 / 本科</p></div></div></div><div><h3>experience</h3>{experience.map(([date,company,role,desc])=><div className="experience-item" key={company}><time>{date.split(' - ').map(x=><span key={x}>{x}<br/></span>)}</time><div><strong>{role}</strong><p>{company}</p><small>{desc}</small></div></div>)}</div><div><h3>skills</h3><p className="skills">Photoshop / Illustrator<br/>After Effects / Cinema 4D<br/>Midjourney / Stable Diffusion</p></div></aside></section>}
function Index(){return <section id="work" className="index light-section"><Reveal className="index-title"><p>Selected works</p><h2>A closer<br/>look.</h2></Reveal><div className="index-list">{categories.map(([id,num,cn,en])=><a key={id} href={toSection(id)}><span className="index-number">{num}.</span><span><strong>{en}</strong><small>{cn}</small></span><ArrowUpRight/></a>)}</div></section>}
function BrandGallery(){const wrap=useRef();const track=useRef();const animation=useRef();const reduce=useReducedMotion();useLayoutEffect(()=>{const mm=gsap.matchMedia();if(!reduce)mm.add('(min-width: 1024px)',()=>{const ctx=gsap.context(()=>{animation.current=gsap.to(track.current,{x:()=>-(track.current.scrollWidth-wrap.current.clientWidth),ease:'none',scrollTrigger:{trigger:wrap.current,start:'top top',end:()=>`+=${track.current.scrollWidth-wrap.current.clientWidth}`,pin:true,scrub:1,invalidateOnRefresh:true}})},wrap);return()=>{ctx.revert();animation.current=null}});return()=>mm.revert()},[reduce]);function move(direction){const st=animation.current?.scrollTrigger;if(st){const positions=[0,...Array.from(track.current.querySelectorAll('.brand-card')).map(el=>Math.min(st.end-st.start,el.offsetLeft-40))];const current=window.scrollY-st.start;const next=direction>0?positions.find(p=>p>current+30):positions.toReversed().find(p=>p<current-30);window.scrollTo({top:st.start+(next??(direction>0?st.end-st.start:0)),behavior:'smooth'})}else track.current.scrollBy({left:direction*track.current.clientWidth*.85,behavior:reduce?'instant':'smooth'})}return <section id="brands" ref={wrap} className="brands light-section"><div ref={track} className="brand-track"><div className="brand-intro"><p>Brand projects</p><h2>Selected work<br/>& explorations</h2><a href={toProject('navee')} className="underlink">View project <ArrowRight/></a></div>{brands.map((p,i)=><article className="brand-card" key={p.id}><a href={toProject(p.id)} className="brand-image" aria-label={`查看 ${p.name} 项目`}><Picture src={p.image} alt={`${p.name} 品牌视觉设计`} /></a><div className="brand-caption"><div><h3>{p.name}</h3><p>{p.description}</p></div><a className="underlink" href={toProject(p.id)}>Explore project <ArrowUpRight/></a></div></article>)}</div><div className="gallery-controls"><span>品牌项目 / 5 projects</span><div><button onClick={()=>move(-1)} aria-label="上一个品牌项目"><ArrowLeft/></button><button onClick={()=>move(1)} aria-label="下一个品牌项目"><ArrowRight/></button></div></div></section>}
function Features(){return <section id="features" className="features light-section"><Reveal className="center-heading"><h2>Feature pages</h2><p>从产品洞察出发，让每一屏都讲述同一个故事。</p></Reveal><div className="feature-grid">{features.map((p,i)=><Reveal key={p.id}><a className={`feature-card feature-${i}`} href={toProject(p.id)}><span className="feature-label">{['WEARABLE TECHNOLOGY','COLOR FROM NATURE','DESIGNED FOR CARE'][i]}</span><Picture src={p.image} alt={p.name}/><div><h3>{p.name}</h3><span>Explore <ArrowUpRight/></span></div></a></Reveal>)}</div><p className="feature-footer">产品叙事 / 视觉概念 / 页面设计</p></section>}
function Products(){return <section id="products" className="products light-section"><div className="product-label"><h2>Product<br/>stories</h2><p>产品详情设计</p></div><div className="product-list">{products.map(p=><Reveal key={p.id} className="product-row"><a href={toProject(p.id)} className="product-image" aria-label={`查看${p.name}详情`}><Picture src={p.image} alt={`${p.name}产品详情设计`}/></a><div className="product-copy"><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><p>{p.approach}</p><a href={toProject(p.id)} className="underlink">View project <ArrowUpRight/></a></div></div></Reveal>)}</div></section>}
function Campaigns(){return <section id="campaigns" className="campaigns dark-section"><div className="campaign-heading"><h2>Campaign visuals</h2><p>主题活动视觉</p></div>{campaigns.map((p,i)=><Reveal className="campaign-row" key={p.id}><div className="campaign-copy"><div><p className="campaign-number">Project 0{i+1}</p><h3>{['Anniversary','Christmas',"Mother’s Day"][i]}</h3><p>{p.name}</p></div><div><p>[ Visual Direction ]</p><p>{p.description}</p><p>{p.approach}</p><a className="underlink" href={toProject(p.id)}>Explore visual <ArrowUpRight/></a></div></div><a href={toProject(p.id)} className="campaign-image" aria-label={`查看${p.name}活动视觉`}><Picture src={p.image} alt={`${p.name}活动视觉`}/></a></Reveal>)}</section>}
function Tilt({item,onClick}){
 const reduce=useReducedMotion();const rx=useMotionValue(0),ry=useMotionValue(0),rz=useMotionValue(0),zoom=useMotionValue(1);
 const config={stiffness:180,damping:18};const sx=useSpring(rx,config),sy=useSpring(ry,config),sz=useSpring(rz,config),scale=useSpring(zoom,config);const bounds=useRef(null);
 const reset=()=>{rx.set(0);ry.set(0);rz.set(0);zoom.set(1)};
 return <motion.button className={`art-card ${item.type}`} style={{rotateX:sx,rotateY:sy,rotateZ:sz,scale,transformPerspective:650}} onPointerEnter={e=>{bounds.current=e.currentTarget.getBoundingClientRect()}} onPointerMove={e=>{if(reduce||e.pointerType==='touch')return;const r=bounds.current;if(!r)return;const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;rx.set(-y*32);ry.set(x*38);rz.set(x*7);zoom.set(1.055)}} onPointerLeave={reset} onPointerCancel={reset} onBlur={reset} onClick={onClick} aria-label={`放大${item.name}`}><Picture src={item.image} alt={item.name}/></motion.button>
}
function Masonry({items,onSelect}){
 const [columns,setColumns]=useState(()=>matchMedia('(max-width:767px)').matches?2:3);
 useEffect(()=>{const query=matchMedia('(max-width:767px)');const update=()=>setColumns(query.matches?2:3);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 const size=Math.ceil(items.length/columns);
 return <div className="art-masonry">{Array.from({length:columns},(_,column)=><div className="art-column" key={column}>{items.filter((_,index)=>index%columns===column).map(p=><Tilt key={p.image} item={p} onClick={()=>onSelect(p)}/>)}</div>)}</div>
}
function Other(){
 const [selected,setSelected]=useState(null);const dialog=useRef();const trigger=useRef();
 useEffect(()=>{if(selected){dialog.current.showModal();return()=>{dialog.current?.close();trigger.current?.focus()}}},[selected]);
 return <section id="other" className="other dark-section"><div className="other-layout"><div className="art-collections"><div className="art-collection"><div className="art-group-heading"><h3>Creative Visuals</h3><span>广告素材</span></div><Masonry items={art} onSelect={p=>{trigger.current=document.activeElement;setSelected(p)}}/></div></div><div className="other-copy"><h2>Beyond<br/>the brief.</h2><p>其他设计 / Creative explorations</p><h3>从穿搭灵感，到产品想象。</h3><p>以服装、光影与材质展开视觉实验。先呈现季节穿搭与生活方式，再探索美甲工具、智能出行和产品结构的创意表达。</p><p>Fashion / Product visuals<br/>AI image-making / Art direction</p><small>悬停探索画面，点击查看完整海报。</small></div></div><dialog ref={dialog} className="lightbox" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}>{selected&&<><button className="lightbox-close" onClick={()=>setSelected(null)} aria-label="关闭大图"><X/></button><Picture src={selected.image} alt={selected.name} eager/><p>{selected.name}</p></>}</dialog></section>
}
function Contact(){return <section id="contact" className="contact dark-section"><div className="contact-heading"><p>Have a project in mind?</p><h2>Let’s make<br/>it <a href={`mailto:${profile.email}`}>happen.<ArrowUpRight/></a></h2></div><div className="contact-details"><p>品牌视觉、产品页面，或一个新的创意。<br/>欢迎与我聊聊。</p><div><span>Email</span><a href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight/></a></div><div><span>WeChat</span><CopyButton value={profile.wechat} label="微信号"/></div><div><span>Phone</span><a href={`tel:${profile.phone}`}>{profile.phone}<ArrowUpRight/></a></div><a className="underlink" href={A+"bess-resume.pdf"} target="_blank" rel="noreferrer">查看完整简历 <ArrowUpRight/></a></div></section>}
function Closing(){return <footer className="closing dark-section"><div className="closing-art"><Picture src={closingImage} className="ambient-video" alt="抽象金属质感封底"/><HeroRipple/></div><div className="closing-meta"><p>BESS ZHANG<br/>CROSS-BORDER E-COMMERCE DESIGNER</p><a href={toSection('home')}>Back to top <ArrowUpRight/></a><a href={`mailto:${profile.email}`}>{profile.email}</a></div><h2>THANK YOU</h2><div className="copyright"><span>© {new Date().getFullYear()} Bess Zhang</span><a href="#/">Replay intro <Play/></a></div></footer>}
function Portfolio({hash}){useEffect(()=>{let cancelled=false;let timer;let frame;const scrollToTarget=()=>{ScrollTrigger.refresh();frame=requestAnimationFrame(()=>{if(!cancelled){if(restorePortfolio&&portfolioReturn){window.scrollTo({top:portfolioReturn.y,behavior:'instant'});restorePortfolio=false}else if(hash.split('/')[2]==='about'&&ScrollTrigger.getById('intro-scene'))window.scrollTo({top:ScrollTrigger.getById('intro-scene').end,behavior:'instant'});else if(hash.split('/')[2]==='home')window.scrollTo({top:0,behavior:'instant'});else document.getElementById(hash.split('/')[2]||'home')?.scrollIntoView({behavior:'instant',block:'start'})}})};document.fonts.ready.then(()=>{if(!cancelled)timer=setTimeout(scrollToTarget,350)});return()=>{cancelled=true;clearTimeout(timer);cancelAnimationFrame(frame)}},[hash]);return <><Nav/><main><IntroSequence><Hero/><About/></IntroSequence><Index/><BrandGallery/><Features/><Products/><Campaigns/><BannerShowcase/><Other/><Contact/></main><Closing/></>}
function Project({project:p}){const [tab,setTab]=useState('challenge');const tabs=[['challenge','The challenge'],['approach','Approach'],['outcome','The work']];useEffect(()=>{window.scrollTo(0,0);setTab('challenge');document.title=`${p.name} | Bess Zhang`},[p.id]);const siblings=allProjects.filter(x=>x.category===p.category);const next=siblings[(siblings.findIndex(x=>x.id===p.id)+1)%siblings.length];return <div className="project-page dark-section"><Nav/><main className="project-layout"><aside className="project-info"><a className="back-link" href={portfolioReturn?.hash||toSection(p.category)}><ArrowLeft/> Back to work</a><div><p className="eyebrow">{categories.find(x=>x[0]===p.category)?.[3]}</p><h1>{p.name}</h1><p>{p.description}</p><ul>{p.services.map(s=><li key={s}>{s}</li>)}</ul></div><div className="project-narrative"><div className="project-tabs" role="tablist" aria-label="项目介绍">{tabs.map(([id,label],i)=><button id={`tab-${id}`} role="tab" aria-controls="project-panel" aria-selected={tab===id} tabIndex={tab===id?0:-1} key={id} onClick={()=>setTab(id)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const target=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setTab(tabs[target][0]);document.getElementById(`tab-${tabs[target][0]}`).focus()}}}>{label}</button>)}</div><p id="project-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>{p[tab]}</p></div><div className="project-next"><a href={portfolioReturn?.hash||toSection(p.category)}>Back to work</a><a href={toProject(next.id)}>Next / {next.name}<ArrowRight/></a></div></aside><div className={`project-images ${p.category==='products'?'product-detail-gallery':''}`}>{p.category==='products'?<><h2 className="detail-gallery-title">{p.id==='nails'?'PRESS ON NAILS':p.id==='vacuum'?'NAIL DUST COLLECTOR':'NAIL DRILL'}</h2><div className="product-main-grid" aria-label="产品主图与副图">{p.mainImages.map((src,i)=><a key={src} href={A+src} target="_blank" rel="noreferrer" aria-label={`查看${p.name}主图 ${i+1} 完整图片`}><Picture src={src} alt={`${p.name}主图与副图 ${i+1}`} eager={i<3}/></a>)}</div><div className="product-long-images" aria-label="产品详情页">{p.detailImages.map((src,i)=><Picture key={src} src={src} alt={`${p.name}完整详情页 ${i+1}`}/>)}</div></>:p.gallery.map((src,i)=><Picture key={src} src={src} alt={`${p.name}作品展示 ${i+1}`} eager={i===0}/>)}</div></main><Contact/></div>}
function App(){const [hash,setHash]=useState(location.hash||'#/');useEffect(()=>{history.scrollRestoration='manual';const capture=e=>{const a=e.target.closest?.('a[href]');if(a?.hash.startsWith('#/project/')&&location.hash.startsWith('#/portfolio'))portfolioReturn={hash:location.hash,y:window.scrollY}};const listen=e=>{if(e.oldURL.includes('#/project/')&&location.hash===portfolioReturn?.hash)restorePortfolio=true;setHash(location.hash||'#/')};document.addEventListener('click',capture,true);window.addEventListener('hashchange',listen);return()=>{window.removeEventListener('hashchange',listen);document.removeEventListener('click',capture,true)}},[]);useEffect(()=>{if(!hash.startsWith('#/project/'))document.title='Bess Zhang | 跨境电商视觉设计师'},[hash]);if(hash.startsWith('#/project/')){const p=allProjects.find(p=>p.id===hash.split('/')[2]);return p?<Project project={p}/>:<main className="not-found"><h1>这个项目暂时不存在。</h1><a href={toSection('work')}>返回作品目录 <ArrowRight/></a></main>}return hash.startsWith('#/portfolio')?<Portfolio hash={hash}/>:<Entrance/>}
const root=import.meta.hot?.data.root??createRoot(document.getElementById('root'));
if(import.meta.hot)import.meta.hot.data.root=root;
root.render(<React.StrictMode><App/></React.StrictMode>);
